import io
import uuid

import boto3
from PIL import Image, ImageOps, UnidentifiedImageError

from app.config import settings

S3_OBSERVATION_PREFIX = "observations/"
S3_THUMBNAIL_PREFIX = "thumbnails/"
CONTENT_TYPE_TO_EXT = {
    "image/jpeg": "jpg",
    "image/png": "png",
    "image/webp": "webp",
}
try:
    RESAMPLE_LANCZOS = Image.Resampling.LANCZOS
except AttributeError:  # Pillow<9 fallback
    RESAMPLE_LANCZOS = Image.LANCZOS


def get_s3_client():
    return boto3.client(
        "s3",
        endpoint_url=f"http://{settings.minio_endpoint}",
        aws_access_key_id=settings.minio_root_user,
        aws_secret_access_key=settings.minio_root_password,
    )


def ensure_bucket():
    client = get_s3_client()
    try:
        client.head_bucket(Bucket=settings.minio_bucket)
    except Exception:
        client.create_bucket(Bucket=settings.minio_bucket)


def normalize_content_type(content_type: str) -> str:
    return content_type.split(";", 1)[0].strip().lower()


def ensure_allowed_content_type(content_type: str) -> str:
    normalized = normalize_content_type(content_type)
    if normalized not in settings.media_allowed_content_types:
        raise ValueError("Unsupported media content_type")
    return normalized


def ensure_media_size(file_size: int | None):
    if file_size is not None and file_size > settings.media_max_upload_bytes:
        raise ValueError("File is too large")


def _ensure_image_pixel_budget(image: Image.Image) -> None:
    width, height = image.size
    if width * height > settings.media_max_image_pixels:
        raise ValueError("Image exceeds maximum pixel budget")


def _resize_for_dimension_limit(image: Image.Image) -> Image.Image:
    width, height = image.size
    max_dimension = max(width, height)
    limit = settings.media_max_image_dimension
    if max_dimension <= limit:
        return image.copy()

    scale = limit / max_dimension
    resized_width = max(1, int(width * scale))
    resized_height = max(1, int(height * scale))
    return image.resize((resized_width, resized_height), RESAMPLE_LANCZOS)


def _load_and_normalize_image(client, s3_key: str) -> Image.Image:
    try:
        response = client.get_object(Bucket=settings.minio_bucket, Key=s3_key)
    except Exception as exc:
        raise RuntimeError("Failed to fetch uploaded media for processing") from exc

    try:
        with Image.open(response["Body"]) as source_image:
            _ensure_image_pixel_budget(source_image)
            normalized = ImageOps.exif_transpose(source_image)
            return _resize_for_dimension_limit(normalized)
    except UnidentifiedImageError as exc:
        raise ValueError("Uploaded media is not a valid image file") from exc
    except OSError as exc:
        raise ValueError("Uploaded media is not a valid image file") from exc
    except ValueError:
        raise
    except Exception as exc:
        raise RuntimeError("Failed to process uploaded media") from exc


def is_valid_observation_key(s3_key: str) -> bool:
    return (
        s3_key.startswith(S3_OBSERVATION_PREFIX)
        and ".." not in s3_key
        and len(s3_key) <= 500
    )


def generate_upload_url(filename: str, content_type: str, file_size: int | None = None) -> dict:
    del filename  # Key is generated by backend to avoid trusting client path/extension.
    normalized_content_type = ensure_allowed_content_type(content_type)
    ensure_media_size(file_size)
    ensure_bucket()
    client = get_s3_client()
    ext = CONTENT_TYPE_TO_EXT.get(normalized_content_type, "jpg")
    key = f"{S3_OBSERVATION_PREFIX}{uuid.uuid4().hex}.{ext}"
    url = client.generate_presigned_url(
        "put_object",
        Params={
            "Bucket": settings.minio_bucket,
            "Key": key,
            "ContentType": normalized_content_type,
        },
        ExpiresIn=600,
    )
    return {"upload_url": url, "s3_key": key, "content_type": normalized_content_type}


def validate_uploaded_object(s3_key: str, expected_content_type: str | None = None) -> tuple[str, int]:
    if not is_valid_observation_key(s3_key):
        raise ValueError("Invalid media key")

    client = get_s3_client()
    try:
        head = client.head_object(Bucket=settings.minio_bucket, Key=s3_key)
    except Exception as exc:
        raise ValueError("Uploaded media not found in storage") from exc

    content_type = normalize_content_type(head.get("ContentType", ""))
    ensure_allowed_content_type(content_type)

    if expected_content_type is not None:
        expected = ensure_allowed_content_type(expected_content_type)
        if expected != content_type:
            raise ValueError("Uploaded media content_type mismatch")

    size = int(head.get("ContentLength", 0))
    ensure_media_size(size)
    return content_type, size


def _build_thumbnail_payload(image: Image.Image) -> bytes:
    thumb = image.copy()
    thumb.thumbnail((settings.media_thumbnail_size, settings.media_thumbnail_size), RESAMPLE_LANCZOS)
    output = io.BytesIO()
    thumb.convert("RGB").save(output, format="JPEG", quality=80, optimize=True)
    return output.getvalue()


def create_thumbnail_from_image(
    s3_key: str, image: Image.Image, client=None
) -> str | None:
    thumb_key = s3_key.replace(S3_OBSERVATION_PREFIX, S3_THUMBNAIL_PREFIX, 1)
    thumbnail_payload = _build_thumbnail_payload(image)
    try:
        s3_client = client or get_s3_client()
        s3_client.put_object(
            Bucket=settings.minio_bucket,
            Key=thumb_key,
            Body=thumbnail_payload,
            ContentType="image/jpeg",
        )
        return thumb_key
    except Exception:
        return None


def create_thumbnail(s3_key: str) -> str | None:
    try:
        client = get_s3_client()
        processed_image = _load_and_normalize_image(client, s3_key)
        return create_thumbnail_from_image(s3_key, processed_image, client=client)
    except Exception:
        return None


def get_media_url(s3_key: str) -> str:
    client = get_s3_client()
    return client.generate_presigned_url(
        "get_object",
        Params={"Bucket": settings.minio_bucket, "Key": s3_key},
        ExpiresIn=3600,
    )


def _serialize_image(image: Image.Image, content_type: str) -> bytes | None:
    output = io.BytesIO()
    if content_type == "image/jpeg":
        normalized = image.convert("RGB")
        normalized.save(output, format="JPEG", quality=85, optimize=True)
    elif content_type == "image/png":
        normalized = image if image.mode in {"RGB", "RGBA", "L", "LA"} else image.convert("RGBA")
        normalized.save(output, format="PNG", optimize=True)
    elif content_type == "image/webp":
        normalized = image if image.mode != "P" else image.convert("RGBA")
        normalized.save(output, format="WEBP", quality=82, method=6)
    else:
        return None
    return output.getvalue()


def optimize_image_object(s3_key: str, content_type: str) -> Image.Image | None:
    if not content_type.startswith("image/"):
        return None

    client = get_s3_client()
    processed_image = _load_and_normalize_image(client, s3_key)
    payload = _serialize_image(processed_image, content_type)

    if payload is None:
        return None
    ensure_media_size(len(payload))

    try:
        client.put_object(
            Bucket=settings.minio_bucket,
            Key=s3_key,
            Body=payload,
            ContentType=content_type,
        )
    except Exception as exc:
        raise RuntimeError("Failed to store processed media") from exc
    return processed_image
