// Generated by scripts/build_media_rights_audit.py.
// Safe media URLs are sourced from docs/content-rights/media-audit.csv.
export const mediaRightsHeroImage = '/img/swan-hero.png'

export const mediaRightsGroupCovers: Record<string, string> = {
  'birds': '/img/group-covers/birds.jpg',
  'fungi': '/img/group-covers/fungi.jpg',
  'herpetofauna': '/img/group-covers/herpetofauna.jpg',
  'insects': '/img/group-covers/insects.jpg',
  'mammals': '/img/group-covers/mammals.jpg',
  'plants': '/img/group-covers/plants.jpg',
}
