#!/usr/bin/env python3
from __future__ import annotations

import csv
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
AUDIT_CSV = ROOT / "docs" / "content-rights" / "media-audit.csv"
OUTPUT_TS = ROOT / "frontend" / "src" / "data" / "mediaAttributionsGenerated.ts"


def _app_url(local_path: str) -> str:
    if local_path.startswith("backend/media/"):
        return "/api/media/" + local_path.removeprefix("backend/media/")
    if local_path.startswith("frontend/public/"):
        return "/" + local_path.removeprefix("frontend/public/")
    return local_path


def _change_note(row: dict[str, str]) -> str:
    notes = row.get("notes", "")
    if "normalized to local JPEG without EXIF" in notes:
        return "Файл нормализован для сайта: локальная копия JPEG без EXIF/метаданных."
    if "generated by product owner" in notes.lower():
        return "Изображение сгенерировано владельцем проекта."
    if row.get("type") == "frontend_image":
        return "Используется как оформительский материал интерфейса."
    return ""


def main() -> int:
    with AUDIT_CSV.open(newline="", encoding="utf-8-sig") as handle:
        rows = list(csv.DictReader(handle))

    active_rows = [
        row
        for row in rows
        if row.get("status") == "verified"
        and row.get("decision") in {"use", "use_until_written_permission"}
        and row.get("local_path")
    ]

    payload = []
    for row in active_rows:
        payload.append(
            {
                "assetId": row.get("asset_id", ""),
                "type": row.get("type", ""),
                "section": row.get("section", ""),
                "nameRu": row.get("name_ru", ""),
                "nameLatin": row.get("name_latin", ""),
                "localPath": row.get("local_path", ""),
                "appUrl": _app_url(row.get("local_path", "")),
                "sourceUrl": row.get("source_url", ""),
                "sourcePage": row.get("source_page", ""),
                "author": row.get("author", ""),
                "license": row.get("license", ""),
                "licenseUrl": row.get("license_url", ""),
                "attributionRequired": row.get("attribution_required") == "yes",
                "status": row.get("status", ""),
                "risk": row.get("risk", ""),
                "decision": row.get("decision", ""),
                "notes": row.get("notes", ""),
                "changeNote": _change_note(row),
            }
        )

    OUTPUT_TS.write_text(
        "\n".join(
            [
                "// Generated by scripts/build_media_attributions.py.",
                "// Source: docs/content-rights/media-audit.csv.",
                "export interface MediaAttribution {",
                "  assetId: string",
                "  type: string",
                "  section: string",
                "  nameRu: string",
                "  nameLatin: string",
                "  localPath: string",
                "  appUrl: string",
                "  sourceUrl: string",
                "  sourcePage: string",
                "  author: string",
                "  license: string",
                "  licenseUrl: string",
                "  attributionRequired: boolean",
                "  status: string",
                "  risk: string",
                "  decision: string",
                "  notes: string",
                "  changeNote: string",
                "}",
                "",
                f"export const mediaAttributions: MediaAttribution[] = {json.dumps(payload, ensure_ascii=False, indent=2)}",
                "",
                "const mediaAttributionByAppUrl = new Map(mediaAttributions.map((item) => [item.appUrl, item]))",
                "",
                "export function normalizeMediaUrl(url?: string | null): string {",
                "  if (!url) return ''",
                "  try {",
                "    const parsed = new URL(url, window.location.origin)",
                "    return parsed.pathname",
                "  } catch {",
                "    return url.split('?')[0].split('#')[0]",
                "  }",
                "}",
                "",
                "export function getMediaAttributionByUrl(url?: string | null): MediaAttribution | undefined {",
                "  return mediaAttributionByAppUrl.get(normalizeMediaUrl(url))",
                "}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"Wrote {len(payload)} attributions to {OUTPUT_TS.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
