"""Apply media rights decisions from docs/content-rights/media-audit.csv.

Generated by scripts/build_media_rights_audit.py. Do not edit mapping by hand;
regenerate the audit when media rights decisions change.
"""
from __future__ import annotations

from typing import Any

from sqlalchemy import or_
from sqlalchemy.orm import Session

from app.models.observation import Observation, ObsMedia
from app.models.species import Species

SPECIES_PHOTO_URLS: dict[str, list[str] | None] = {
    'Ёж обыкновенный': ['/api/media/species/erinaceus-europaeus.jpg'],
    'Бабочка лимонница': ['/api/media/species/gonepteryx-rhamni.jpg'],
    'Байбак': ['/api/media/species/marmota-bobak.jpg'],
    'Балобан': ['/api/media/species/falco-cherrug.jpg'],
    'Барсук': ['/api/media/species/meles-meles.jpg'],
    'Бассия венечная': ['/api/media/species/bassia-scoparia.jpg'],
    'Белоспинный дятел': ['/api/media/species/dendrocopos-leucotos.jpg'],
    'Белянка (капустница)': ['/api/media/species/pieris-brassicae.jpg'],
    'Беркут': ['/api/media/species/aquila-chrysaetos.jpg'],
    'Берёза повислая': ['/api/media/species/betula-pendula.jpg'],
    'Берёзовый шелкопряд': ['/api/media/species/endromis-versicolora.jpg'],
    'Благородный олень': ['/api/media/species/cervus-elaphus.jpg'],
    'Бледная поганка': ['/api/media/species/amanita-phalloides.jpg'],
    'Бобр': ['/api/media/species/castor-fiber.jpg'],
    'Богомол': ['/api/media/species/mantis-religiosa.jpg'],
    'Бодяк полевой': ['/api/media/species/cirsium-arvense.jpg'],
    'Божья коровка': ['/api/media/species/coccinellidae.jpg'],
    'Болотная черепаха': ['/api/media/species/emys-orbicularis.jpg'],
    'Большая белая цапля': ['/api/media/species/ardea-alba.jpg'],
    'Большая выпь': ['/api/media/species/botaurus-stellaris.jpg'],
    'Большая ежемуха': ['/api/media/species/tachina-grossa.jpg'],
    'Большая синица': ['/api/media/species/parus-major.jpg'],
    'Большое коромысло': ['/api/media/species/aeshna-grandis.jpg'],
    'Большой веретенник': ['/api/media/species/limosa-limosa.jpg'],
    'Большой подорлик': ['/api/media/species/clanga-clanga.jpg'],
    'Большой рогохвост': ['/api/media/species/urocerus-gigas.jpg'],
    'Брандушка разноцветная': ['/api/media/species/bulbocodium-versicolor.jpg'],
    'Бронзовка гладкая': ['/api/media/species/protaetia-aeruginosa.jpg'],
    'Брусника': ['/api/media/species/vaccinium-vitis-idaea.jpg'],
    'Ветреница лесная': ['/api/media/species/anemone-sylvestris.jpg'],
    'Волчек (малая выпь)': ['/api/media/species/ixobrychus-minutus.jpg'],
    'Вольвариелла шелковистая': ['/api/media/species/volvariella-bombycina.jpg'],
    'Вольфия бескорневая': ['/api/media/species/wolffia-arrhiza.jpg'],
    'Выхухоль русская': ['/api/media/species/desmana-moschata.jpg'],
    'Вьюнковый бражник': ['/api/media/species/agrius-convolvuli.jpg'],
    'Вяз приземистый': ['/api/media/species/ulmus-pumila.jpg'],
    'Гадюка Никольского': ['/api/media/species/vipera-nikolskii.jpg'],
    'Галатея': ['/api/media/species/melanargia-galathea.jpg'],
    'Галка': ['/api/media/species/coloeus-monedula.jpg'],
    'Гвоздика песчаная': ['/api/media/species/dianthus-arenarius.jpg'],
    'Головач гигантский': ['/api/media/species/calvatia-gigantea.jpg'],
    'Голубая ленточница': ['/api/media/species/catocala-fraxini.jpg'],
    'Голубянка аргирогномон': ['/api/media/species/plebejus-argyrognomon.jpg'],
    'Голубянка красивая': ['/api/media/species/polyommatus-bellargus.jpg'],
    'Горлица': ['/api/media/species/streptopelia-turtur.jpg'],
    'Горошек мышиный': ['/api/media/species/vicia-cracca.jpg'],
    'Грач': ['/api/media/species/corvus-frugilegus.jpg'],
    'Гребенчатый тритон': ['/api/media/species/triturus-cristatus.jpg'],
    'Грушанка зеленоцветковая': ['/api/media/species/pyrola-chlorantha.jpg'],
    'Длиннохвостая неясыть': ['/api/media/species/strix-uralensis.jpg'],
    'Дневной павлиний глаз': ['/api/media/species/aglais-io.jpg'],
    'Дозорщик император': ['/api/media/species/anax-imperator.jpg'],
    'Домовый воробей': ['/api/media/species/passer-domesticus.jpg'],
    'Донник белый': ['/api/media/species/melilotus-albus.jpg'],
    'Дровосек кожевенник': ['/api/media/species/prionus-coriarius.jpg'],
    'Дуб': ['/api/media/species/quercus-robur.jpg'],
    'Дупель': ['/api/media/species/gallinago-media.jpg'],
    'Желна': ['/api/media/species/dryocopus-martius.jpg'],
    'Живородящая ящерица': ['/api/media/species/zootoca-vivipara.jpg'],
    'Жук мягкотелка': ['/api/media/species/cantharidae.jpg'],
    'Жук-носорог': ['/api/media/species/oryctes-nasicornis.jpg'],
    'Жук-плавунец широчайший': ['/api/media/species/dytiscus-latissimus.jpg'],
    'Заяц-беляк': ['/api/media/species/lepus-timidus.jpg'],
    'Заяц-русак': ['/api/media/species/lepus-europaeus.jpg'],
    'Змееяд': ['/api/media/species/circaetus-gallicus.jpg'],
    'Ива лопарская': ['/api/media/species/salix-lapponum.jpg'],
    'Иван-чай узколистный': ['/api/media/species/chamaenerion-angustifolium.jpg'],
    'Кабан': ['/api/media/species/sus-scrofa.jpg'],
    'Каштановый гриб': ['/api/media/species/gyroporus-castaneus.jpg'],
    'Клавария цоллинегра': ['/api/media/species/clavaria-zollingeri.jpg'],
    'Клевер ползучий': ['/api/media/species/trifolium-repens.jpg'],
    'Клен': ['/api/media/species/acer-platanoides.jpg'],
    'Клинтух': ['/api/media/species/columba-oenas.jpg'],
    'Клоп солдат': ['/api/media/species/pyrrhocoris-apterus.jpg'],
    'Ковыль перистый': ['/api/media/species/stipa-pennata.jpg'],
    'Козодой': ['/api/media/species/caprimulgus-europaeus.jpg'],
    'Колокольчик широколистный': ['/api/media/species/campanula-latifolia.jpg'],
    'Короед': ['/api/media/species/scolytinae.jpg'],
    'Коромысло зелёное': ['/api/media/species/aeshna-viridis.jpg'],
    'Костёр растопыренный': ['/api/media/species/bromus-squarrosus.jpg'],
    'Косуля': ['/api/media/species/capreolus-capreolus.jpg'],
    'Красношейная поганка': ['/api/media/species/podiceps-auritus.jpg'],
    'Красотка-девушка': ['/api/media/species/calopteryx-virgo.jpg'],
    'Крыса серая': ['/api/media/species/rattus-norvegicus.jpg'],
    'Кувшинка снежно-белая': ['/api/media/species/nymphaea-candida.jpg'],
    'Кулик-сорока': ['/api/media/species/haematopus-ostralegus.jpg'],
    'Лапчатка гусиная': ['/api/media/species/argentina-anserina.jpg'],
    'Ласточка деревенская': ['/api/media/species/hirundo-rustica.jpg'],
    'Латук компасный': ['/api/media/species/lactuca-serriola.jpg'],
    'Лесная соня': ['/api/media/species/dryomys-nitedula.jpg'],
    'Лесной жаворонок': ['/api/media/species/lullula-arborea.jpg'],
    'Липа': ['/api/media/species/tilia-cordata.jpg'],
    'Лисица обыкновенная': ['/api/media/species/vulpes-vulpes.jpg'],
    'Листоед роди': ['/api/media/species/chrysolina.jpg'],
    'Ломкая веретеница': ['/api/media/species/anguis-fragilis.jpg'],
    'Лось': ['/api/media/species/alces-alces.jpg'],
    'Льнянка обыкновенная': ['/api/media/species/linaria-vulgaris.jpg'],
    'Любка двулистная': ['/api/media/species/platanthera-bifolia.jpg'],
    'Люцерна хмелевидная': ['/api/media/species/medicago-lupulina.jpg'],
    'Малая вечерница': ['/api/media/species/nyctalus-leisleri.jpg'],
    'Малая поганка': ['/api/media/species/tachybaptus-ruficollis.jpg'],
    'Малиновая ленточница': ['/api/media/species/catocala-sponsa.jpg'],
    'Мать-и-мачеха обыкновенная': ['/api/media/species/tussilago-farfara.jpg'],
    'Махаон': ['/api/media/species/papilio-machaon.jpg'],
    'Медведица гера': ['/api/media/species/euplagia-quadripunctaria.jpg'],
    'Медведица госпожа': ['/api/media/species/callimorpha-dominula.jpg'],
    'Медведица четырёхточечная': ['/api/media/species/euplagia-quadripunctaria-2.jpg'],
    'Мелангрия галатея': ['/api/media/species/melanargia-galathea-2.jpg'],
    'Можжевельник обыкновенный': ['/api/media/species/juniperus-communis.jpg'],
    'Молодило русское': ['/api/media/species/sempervivum-ruthenicum.jpg'],
    'Мохноногий сыч': ['/api/media/species/aegolius-funereus.jpg'],
    'Моховик': ['/api/media/species/xerocomus.jpg'],
    'Мраморный хрущ': ['/api/media/species/polyphylla-fullo.jpg'],
    'Муравьи': ['/api/media/species/formicidae.jpg'],
    'Мухомор красный': ['/api/media/species/amanita-muscaria.jpg'],
    'Мухомор серебристый': ['/api/media/species/amanita-argentea.jpg'],
    'Мышей зелёный': ['/api/media/species/setaria-viridis.jpg'],
    'Мышь домовая': ['/api/media/species/mus-musculus.jpg'],
    'Мятлик однолетний': None,
    'Неполнокрыл большой': ['/api/media/species/necydalis-major.jpg'],
    'Неравноцветник кровельный': ['/api/media/species/anisantha-tectorum.jpg'],
    'Ночница брандта': ['/api/media/species/myotis-brandtii.jpg'],
    'Обыкновенная белка': ['/api/media/species/sciurus-vulgaris.jpg'],
    'Обыкновенная выдра': ['/api/media/species/lutra-lutra.jpg'],
    'Обыкновенная кукушка': ['/api/media/species/cuculus-canorus.jpg'],
    'Обыкновенная медянка': ['/api/media/species/coronella-austriaca.jpg'],
    'Обыкновенный скворец': ['/api/media/species/sturnus-vulgaris.jpg'],
    'Обыкновенный соловей': ['/api/media/species/luscinia-luscinia.jpg'],
    'Обыкновенный уж': ['/api/media/species/natrix-natrix.jpg'],
    'Обыкновенный языкан': ['/api/media/species/macroglossum-stellatarum.jpg'],
    'Озёрная лягушка': ['/api/media/species/pelophylax-ridibundus.jpg'],
    'Ондатра': ['/api/media/species/ondatra-zibethicus.jpg'],
    'Опенок ложный': ['/api/media/species/hypholoma-fasciculare.jpg'],
    'Орел карлик': ['/api/media/species/hieraaetus-pennatus.jpg'],
    'Орлан белохвост': ['/api/media/species/haliaeetus-albicilla.jpg'],
    'Осина': ['/api/media/species/populus-tremula.jpg'],
    'Осоед': ['/api/media/species/pernis-apivorus.jpg'],
    'Падуболистный коконопряд': ['/api/media/species/gastropacha-quercifolia.jpg'],
    'Пахучий красотел': ['/api/media/species/calosoma-sycophanta.jpg'],
    'Перевязанная стрекоза': ['/api/media/species/sympetrum-pedemontanum.jpg'],
    'Перевязка': ['/api/media/species/vormela-peregusna.jpg'],
    'Пецица сочная': ['/api/media/species/peziza-succosa.jpg'],
    'Плаун булавовидный': ['/api/media/species/lycopodium-clavatum.jpg'],
    'Плаун годичный': ['/api/media/species/lycopodium-annotinum.jpg'],
    'Плаун сплюснутый': ['/api/media/species/diphasiastrum-complanatum.jpg'],
    'Подбел обыкновенный': ['/api/media/species/andromeda-polifolia.jpg'],
    'Подберёзовик': ['/api/media/species/leccinum-scabrum.jpg'],
    'Подорожник большой': ['/api/media/species/plantago-major.jpg'],
    'Подосиновик': ['/api/media/species/leccinum-aurantiacum.jpg'],
    'Полевой лунь': ['/api/media/species/circus-cyaneus.jpg'],
    'Полынь обыкновенная': ['/api/media/species/artemisia-vulgaris.jpg'],
    'Прозерпина': ['/api/media/species/proserpinus-proserpina.jpg'],
    'Прострел раскрытый': ['/api/media/species/pulsatilla-patens.jpg'],
    'Прыткая ящерица': ['/api/media/species/lacerta-agilis.jpg'],
    'Пчела-плотник': ['/api/media/species/xylocopa-valga.jpg'],
    'Рдест длиннейший': ['/api/media/species/potamogeton-praelongus.jpg'],
    'Рдест остролистный': ['/api/media/species/potamogeton-acutifolius.jpg'],
    'Рдест узловатый': ['/api/media/species/potamogeton-nodosus.jpg'],
    'Робиния псевдоакация': ['/api/media/species/robinia-pseudoacacia.jpg'],
    'Рыжая цапля': ['/api/media/species/ardea-purpurea.jpg'],
    'Рябчик русский': ['/api/media/species/fritillaria-ruthenica.jpg'],
    'Саркодон черепитчатый': ['/api/media/species/sarcodon-imbricatus.jpg'],
    'Свинушка тонкая': ['/api/media/species/paxillus-involutus.jpg'],
    'Свиристель': ['/api/media/species/bombycilla-garrulus.jpg'],
    'Седой дятел': ['/api/media/species/picus-canus.jpg'],
    'Серая ворона': ['/api/media/species/corvus-cornix.jpg'],
    'Серая жаба': ['/api/media/species/bufo-bufo.jpg'],
    'Серая неясыть': ['/api/media/species/strix-aluco.jpg'],
    'Серая утка': ['/api/media/species/mareca-strepera.jpg'],
    'Серый рофитоидес': None,
    'Сизый голубь': ['/api/media/species/columba-livia.jpg'],
    'Синеголовник плосколистный': ['/api/media/species/eryngium-planum.jpg'],
    'Синяк обыкновенный': ['/api/media/species/echium-vulgare.jpg'],
    'Сиреневый бражник': ['/api/media/species/sphinx-ligustri.jpg'],
    'Скабиозовая шмелевидка': ['/api/media/species/hemaris-tityus.jpg'],
    'Сколия гигант': ['/api/media/species/megascolia-maculata.jpg'],
    'Снегирь': ['/api/media/species/pyrrhula-pyrrhula.jpg'],
    'Сокол сапсан': ['/api/media/species/falco-peregrinus.jpg'],
    'Сорока': ['/api/media/species/pica-pica.jpg'],
    'Средний винный бражник': ['/api/media/species/deilephila-porcellus.jpg'],
    'Средний пёстрый дятел': ['/api/media/species/dendrocoptes-medius.jpg'],
    'Степная дыбка': ['/api/media/species/saga-pedo.jpg'],
    'Степная пеструшка': ['/api/media/species/lagurus-lagurus.jpg'],
    'Стриж черный': ['/api/media/species/apus-apus.jpg'],
    'Строчок гигантский': ['/api/media/species/gyromitra-gigas.jpg'],
    'Суслик европейский': ['/api/media/species/spermophilus-citellus.jpg'],
    'Сыроежка': ['/api/media/species/russula-sp.jpg'],
    'Татарник колючий': ['/api/media/species/onopordum-acanthium.jpg'],
    'Толстянка обыкновенная': ['/api/media/species/crassula-aquatica.jpg'],
    'Тополевый ленточник': ['/api/media/species/limenitis-populi.jpg'],
    'Тополь черный': ['/api/media/species/populus-nigra.jpg'],
    'Травяная лягушка': ['/api/media/species/rana-temporaria.jpg'],
    'Тритон обыкновенный': ['/api/media/species/lissotriton-vulgaris.jpg'],
    'Трясогузка белая': ['/api/media/species/motacilla-alba.jpg'],
    'Трёхреберник непахучий': ['/api/media/species/tripleurospermum-perforatum.jpg'],
    'Тюльпан лесной': ['/api/media/species/tulipa-sylvestris.jpg'],
    'Узорчатый полоз': ['/api/media/species/elaphe-dione.jpg'],
    'Усач мускусный': ['/api/media/species/aromia-moschata.jpg'],
    'Фиолетовая жужелица': ['/api/media/species/carabus-violaceus.jpg'],
    'Хейлозия Кузнецовой': ['/api/media/species/cheilosia.jpg'],
    'Черная долгоножка': ['/api/media/species/tanyptera-atrata.jpg'],
    'Чернозобая гагара': ['/api/media/species/gavia-arctica.jpg'],
    'Чесночница': ['/api/media/species/pelobates-fuscus.jpg'],
    'Чёрная медведица': ['/api/media/species/epatolmis-luctifera.jpg'],
    'Чёрный аист': ['/api/media/species/ciconia-nigra.jpg'],
    'Чёрный стриж': ['/api/media/species/apus-apus-2.jpg'],
    'Энтолома серо-стальная': ['/api/media/species/entoloma-bloxamii.jpg'],
    'Ясень обыкновенный': ['/api/media/species/fraxinus-excelsior.jpg'],
}

UNSAFE_AUDIO_SPECIES: set[str] = {
    'Ёж обыкновенный',
    'Барсук',
    'Белоспинный дятел',
    'Беркут',
    'Благородный олень',
    'Длиннохвостая неясыть',
    'Желна',
    'Косуля',
    'Кулик-сорока',
    'Лесной жаворонок',
    'Лисица обыкновенная',
    'Мохноногий сыч',
    'Орел карлик',
    'Серая жаба',
    'Сокол сапсан',
    'Травяная лягушка',
    'Чесночница',
}


def _assign_if_changed(species: Species, values: dict[str, Any]) -> bool:
    changed = False
    for key, value in values.items():
        if getattr(species, key) != value:
            setattr(species, key, value)
            changed = True
    return changed


def apply_media_rights_safe(db: Session) -> dict[str, int]:
    summary = {
        'photo_updated': 0,
        'audio_disabled': 0,
        'legacy_observation_media_deleted': 0,
        'unconsented_observation_media_deleted': 0,
        'missing_species': 0,
    }
    for name_ru, photo_urls in SPECIES_PHOTO_URLS.items():
        species = db.query(Species).filter(Species.name_ru == name_ru).first()
        if species is None:
            summary['missing_species'] += 1
            continue
        if species.photo_urls != photo_urls:
            species.photo_urls = photo_urls
            summary['photo_updated'] += 1

    for name_ru in UNSAFE_AUDIO_SPECIES:
        species = db.query(Species).filter(Species.name_ru == name_ru).first()
        if species is None:
            summary['missing_species'] += 1
            continue
        if _assign_if_changed(
            species,
            {
                'audio_url': None,
                'audio_title': None,
                'audio_source': None,
                'audio_license': None,
            },
        ):
            summary['audio_disabled'] += 1

    summary['legacy_observation_media_deleted'] = (
        db.query(ObsMedia)
        .filter(
            or_(
                ObsMedia.s3_key.like('species-pdf/%'),
                ObsMedia.thumbnail_key.like('species-pdf/%'),
            )
        )
        .delete(synchronize_session=False)
    )
    summary['unconsented_observation_media_deleted'] = (
        db.query(ObsMedia)
        .filter(
            ObsMedia.observation_id.in_(
                db.query(Observation.id).filter(
                    Observation.content_notice_accepted_at.is_(None)
                )
            )
        )
        .delete(synchronize_session=False)
    )

    db.flush()
    return summary
