SPECIES_DATA = [
    {"name_ru": "Неравноцветник кровельный", "name_latin": "Anisantha tectorum", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Полынь обыкновенная", "name_latin": "Artemisia vulgaris", "group": "plants", "category": "ruderal", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Artemisia_vulgaris_-_Mugwort_-_Beifu%C3%9F.jpg/640px-Artemisia_vulgaris_-_Mugwort_-_Beifu%C3%9F.jpg"]},
    {"name_ru": "Костёр растопыренный", "name_latin": "Bromus squarrosus", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Бассия венечная", "name_latin": "Bassia scoparia", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Полынь горькая", "name_latin": "Artemisia absinthium", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Лапчатка гусиная", "name_latin": "Argentina anserina", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Донник белый", "name_latin": "Melilotus albus", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Мятлик однолетний", "name_latin": "Poa annua", "group": "plants", "category": "ruderal", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Poa_annua.jpg/640px-Poa_annua.jpg"]},
    {"name_ru": "Татарник колючий", "name_latin": "Onopordum acanthium", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Трёхреберник непахучий", "name_latin": "Tripleurospermum perforatum", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Иван-чай узколистный", "name_latin": "Chamaenerion angustifolium", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Бодяк полевой", "name_latin": "Cirsium arvense", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Подорожник большой", "name_latin": "Plantago major", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Пижма обыкновенная", "name_latin": "Tanacetum vulgare", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Синяк обыкновенный", "name_latin": "Echium vulgare", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Латук компасный", "name_latin": "Lactuca serriola", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Льнянка обыкновенная", "name_latin": "Linaria vulgaris", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Мать-и-мачеха обыкновенная", "name_latin": "Tussilago farfara", "group": "plants", "category": "ruderal", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5e/Tussilago_farfara_050405.jpg/640px-Tussilago_farfara_050405.jpg"]},
    {"name_ru": "Мышей зелёный", "name_latin": "Setaria viridis", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Горошек мышиный", "name_latin": "Vicia cracca", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Люцерна хмелевидная", "name_latin": "Medicago lupulina", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Клевер ползучий", "name_latin": "Trifolium repens", "group": "plants", "category": "ruderal", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Trifolium_repens_in_Kamenicky.jpg/640px-Trifolium_repens_in_Kamenicky.jpg"]},
    {"name_ru": "Робиния псевдоакация", "name_latin": "Robinia pseudoacacia", "group": "plants", "category": "ruderal", "photo_urls": []},
    {"name_ru": "Тополь чёрный", "name_latin": "Populus nigra", "group": "plants", "category": "typical", "photo_urls": []},
    {"name_ru": "Клён ясенелистный", "name_latin": "Acer negundo", "group": "plants", "category": "typical", "photo_urls": []},
    {"name_ru": "Берёза повислая", "name_latin": "Betula pendula", "group": "plants", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Betula_pendula_001.jpg/640px-Betula_pendula_001.jpg"]},
    {"name_ru": "Ива белая", "name_latin": "Salix alba", "group": "plants", "category": "typical", "photo_urls": []},
    {"name_ru": "Ковыль перистый", "name_latin": "Stipa pennata", "group": "plants", "category": "rare", "conservation_status": "Красная книга Липецкой области", "photo_urls": []},
    {"name_ru": "Прострел раскрытый", "name_latin": "Pulsatilla patens", "group": "plants", "category": "red_book", "conservation_status": "Красная книга РФ", "photo_urls": []},
    {"name_ru": "Мухомор красный", "name_latin": "Amanita muscaria", "group": "fungi", "category": "typical", "is_poisonous": True, "description": "Ядовитый гриб с красной шляпкой и белыми точками.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Amanita_muscaria_%2803%29.jpg/640px-Amanita_muscaria_%2803%29.jpg"]},
    {"name_ru": "Бледная поганка", "name_latin": "Amanita phalloides", "group": "fungi", "category": "typical", "is_poisonous": True, "description": "Смертельно ядовитый гриб.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Amanita_phalloides_1.JPG/640px-Amanita_phalloides_1.JPG"]},
    {"name_ru": "Свинушка тонкая", "name_latin": "Paxillus involutus", "group": "fungi", "category": "typical", "is_poisonous": True, "photo_urls": []},
    {"name_ru": "Подберёзовик", "name_latin": "Leccinum scabrum", "group": "fungi", "category": "typical", "photo_urls": []},
    {"name_ru": "Сыроежка", "name_latin": "Russula sp.", "group": "fungi", "category": "typical", "photo_urls": []},
    {"name_ru": "Жук-плавунец широчайший", "name_latin": "Dytiscus latissimus", "group": "insects", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "photo_urls": []},
    {"name_ru": "Коромысло зелёное", "name_latin": "Aeshna viridis", "group": "insects", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "photo_urls": []},
    {"name_ru": "Махаон", "name_latin": "Papilio machaon", "group": "insects", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Papilio_machaon_MHNT.jpg/640px-Papilio_machaon_MHNT.jpg"]},
    {"name_ru": "Пчела-плотник", "name_latin": "Xylocopa valga", "group": "insects", "category": "red_book", "conservation_status": "Красная книга РФ", "photo_urls": []},
    {"name_ru": "Прыткая ящерица", "name_latin": "Lacerta agilis", "group": "herpetofauna", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Lacerta_agilis_male_2012_G1.jpg/640px-Lacerta_agilis_male_2012_G1.jpg"]},
    {"name_ru": "Обыкновенный уж", "name_latin": "Natrix natrix", "group": "herpetofauna", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Natrix_natrix_%28Marek_Szczepanek%29.jpg/640px-Natrix_natrix_%28Marek_Szczepanek%29.jpg"]},
    {"name_ru": "Гадюка Никольского", "name_latin": "Vipera nikolskii", "group": "herpetofauna", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "is_poisonous": True, "do_dont_rules": "Не приближайтесь! Ядовита. При обнаружении сообщите экологу.", "photo_urls": []},
    {"name_ru": "Озёрная лягушка", "name_latin": "Pelophylax ridibundus", "group": "herpetofauna", "category": "typical", "photo_urls": []},
    {"name_ru": "Сизый голубь", "name_latin": "Columba livia", "group": "birds", "category": "synanthropic", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Treron_vernans.jpg/640px-Treron_vernans.jpg"]},
    {"name_ru": "Домовый воробей", "name_latin": "Passer domesticus", "group": "birds", "category": "synanthropic", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Passer_domesticus_male_%2815%29.jpg/640px-Passer_domesticus_male_%2815%29.jpg"]},
    {"name_ru": "Серая ворона", "name_latin": "Corvus cornix", "group": "birds", "category": "synanthropic", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Corvus_cornix_in_Aarhus.jpg/640px-Corvus_cornix_in_Aarhus.jpg"]},
    {"name_ru": "Сорока", "name_latin": "Pica pica", "group": "birds", "category": "synanthropic", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Pica_pica_-_Magpie_-_Elster.jpg/640px-Pica_pica_-_Magpie_-_Elster.jpg"]},
    {"name_ru": "Большая синица", "name_latin": "Parus major", "group": "birds", "category": "synanthropic", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Parus_major_male.jpg/640px-Parus_major_male.jpg"]},
    {"name_ru": "Чёрный стриж", "name_latin": "Apus apus", "group": "birds", "category": "synanthropic", "photo_urls": []},
    {"name_ru": "Обыкновенная кукушка", "name_latin": "Cuculus canorus", "group": "birds", "category": "typical", "photo_urls": []},
    {"name_ru": "Обыкновенный соловей", "name_latin": "Luscinia luscinia", "group": "birds", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d6/Luscinia_luscinia_2_%28Martin_Mecnarowski%29.jpg/640px-Luscinia_luscinia_2_%28Martin_Mecnarowski%29.jpg"]},
    {"name_ru": "Обыкновенный скворец", "name_latin": "Sturnus vulgaris", "group": "birds", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Sturnus_vulgaris_2_%28Martin_Mecnarowski%29.jpg/640px-Sturnus_vulgaris_2_%28Martin_Mecnarowski%29.jpg"]},
    {"name_ru": "Лебедь-шипун", "name_latin": "Cygnus olor", "group": "birds", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "season_info": "Апрель — Октябрь", "description": "Крупная водоплавающая птица семейства утиных. Размах крыльев до 240 см.", "do_dont_rules": "Фотографируйте с расстояния не менее 30 м. Не приближайтесь к гнёздам. Не кормите хлебом.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Cygnus_olor_2_%28Marek_Szczepanek%29.jpg/640px-Cygnus_olor_2_%28Marek_Szczepanek%29.jpg"]},
    {"name_ru": "Серый журавль", "name_latin": "Grus grus", "group": "birds", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "photo_urls": []},
    {"name_ru": "Ёж обыкновенный", "name_latin": "Erinaceus europaeus", "group": "mammals", "category": "typical", "do_dont_rules": "Не берите в руки. Могут переносить бешенство.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Erinaceus_europaeus_LC0119.jpg/640px-Erinaceus_europaeus_LC0119.jpg"]},
    {"name_ru": "Заяц-русак", "name_latin": "Lepus europaeus", "group": "mammals", "category": "typical", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Lepus_europaeus_%28Europese_haas%29.jpg/640px-Lepus_europaeus_%28Europese_haas%29.jpg"]},
    {"name_ru": "Лисица обыкновенная", "name_latin": "Vulpes vulpes", "group": "mammals", "category": "typical", "do_dont_rules": "Не приближайтесь. При агрессивном поведении сообщите экологу.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Vulpes_vulpes_sitting.jpg/640px-Vulpes_vulpes_sitting.jpg"]},
    {"name_ru": "Кабан", "name_latin": "Sus scrofa", "group": "mammals", "category": "typical", "do_dont_rules": "Опасен! Не приближайтесь. Сообщите экологу немедленно.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/6e/Sus_scrofa_scrofa.jpg/640px-Sus_scrofa_scrofa.jpg"]},
    {"name_ru": "Лось", "name_latin": "Alces alces", "group": "mammals", "category": "typical", "do_dont_rules": "Не приближайтесь, особенно к самкам с детёнышами.", "photo_urls": ["https://upload.wikimedia.org/wikipedia/commons/thumb/8/8b/Moose_superior.jpg/640px-Moose_superior.jpg"]},
    {"name_ru": "Крапчатый суслик", "name_latin": "Spermophilus suslicus", "group": "mammals", "category": "red_book", "conservation_status": "Красная книга Липецкой области", "photo_urls": []},
]
