"""initial schema

Revision ID: 4bd6bf7ca83c
Revises: 
Create Date: 2026-04-05 16:14:20.185693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4bd6bf7ca83c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decision_tree',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('suggested_species_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['decision_tree.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_tree_parent_id'), 'decision_tree', ['parent_id'], unique=False)
    op.create_table('site_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('group', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('polygon_count', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # Spatial index is auto-created by GeoAlchemy2
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_latin', sa.String(length=255), nullable=False),
    sa.Column('group', sa.Enum('plants', 'fungi', 'insects', 'herpetofauna', 'birds', 'mammals', name='speciesgroup'), nullable=False),
    sa.Column('category', sa.Enum('ruderal', 'typical', 'rare', 'red_book', 'synanthropic', name='speciescategory'), nullable=False),
    sa.Column('conservation_status', sa.String(length=255), nullable=True),
    sa.Column('is_poisonous', sa.Boolean(), nullable=False),
    sa.Column('season_info', sa.String(length=500), nullable=True),
    sa.Column('biotopes', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('do_dont_rules', sa.Text(), nullable=True),
    sa.Column('qr_url', sa.String(length=500), nullable=True),
    sa.Column('photo_urls', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_species_category'), 'species', ['category'], unique=False)
    op.create_index(op.f('ix_species_group'), 'species', ['group'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('employee', 'ecologist', 'admin', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_external_id'), 'users', ['external_id'], unique=True)
    op.create_table('observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('species_id', sa.Integer(), nullable=True),
    sa.Column('group', sa.String(length=50), nullable=False),
    sa.Column('observed_at', sa.DateTime(), nullable=False),
    sa.Column('location_point', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('site_zone_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('on_review', 'needs_data', 'confirmed', 'rejected', name='observationstatus'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('is_incident', sa.Boolean(), nullable=False),
    sa.Column('incident_type', sa.Enum('injured', 'dead', 'mass_death', 'other', name='incidenttype'), nullable=True),
    sa.Column('incident_severity', sa.Enum('low', 'medium', 'high', 'critical', name='incidentseverity'), nullable=True),
    sa.Column('incident_status', sa.Enum('new', 'in_progress', 'closed', name='incidentstatus'), nullable=True),
    sa.Column('reviewer_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('sensitive_level', sa.Enum('open', 'blurred', 'hidden', name='sensitivelevel'), nullable=False),
    sa.Column('safety_checked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['site_zone_id'], ['site_zones.id'], ),
    sa.ForeignKeyConstraint(['species_id'], ['species.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # Spatial index is auto-created by GeoAlchemy2
    op.create_index(op.f('ix_observations_author_id'), 'observations', ['author_id'], unique=False)
    op.create_index(op.f('ix_observations_status'), 'observations', ['status'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('needs_data', 'confirmed', 'rejected', 'incident_new', name='notificationtype'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('obs_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observation_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('thumbnail_key', sa.String(length=500), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['observation_id'], ['observations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_obs_media_observation_id'), 'obs_media', ['observation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_obs_media_observation_id'), table_name='obs_media')
    op.drop_table('obs_media')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_observations_status'), table_name='observations')
    op.drop_index(op.f('ix_observations_author_id'), table_name='observations')
    op.drop_index('idx_observations_location_point', table_name='observations', postgresql_using='gist')
    op.drop_table('observations')
    op.drop_index(op.f('ix_users_external_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_species_group'), table_name='species')
    op.drop_index(op.f('ix_species_category'), table_name='species')
    op.drop_table('species')
    op.drop_index('idx_site_zones_geom', table_name='site_zones', postgresql_using='gist')
    op.drop_table('site_zones')
    op.drop_index(op.f('ix_decision_tree_parent_id'), table_name='decision_tree')
    op.drop_table('decision_tree')
    # Explicitly cleanup enum types so downgrade->upgrade cycle is reproducible.
    for enum_type in (
        "notificationtype",
        "sensitivelevel",
        "incidentstatus",
        "incidentseverity",
        "incidenttype",
        "observationstatus",
        "userrole",
        "speciescategory",
        "speciesgroup",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_type}")
    # ### end Alembic commands ###
